### PR TITLE
add new playlist

### PR DESCRIPTION
**Pull request by gunturpratama**
ive add new song in this playlist ,need for review perhaps ?

### CODE REVIEW

**Comment by satyawikananda** [comment]
Thanks for PR, but can you put your favorite playlist and not your song? because this repository is just for playlist song and podcast

**Comment by gunturpratama** [comment]
Playlist on Spotify?

**Comment by gunturpratama** [comment]
Okay ill try to fix that

**Comment by gunturpratama** [comment]
hello i was fix the readme and also the conflict in contributor markdown please review my work

**Comment by satyawikananda** [comment]
Thank you

**Comment by satyawikananda** [comment]
@all-contributors please add @gunturpratama as @content

**Pull request merged**
